<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetFrameworkCurrent);$(NetCoreAppCurrent)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(CommonTestPath)System\Numerics\BigNumberTests.cs" Link="BigNumberTests.cs" />
    <Compile Include="MathF.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Microsoft.Bcl.Numerics.csproj" />
  </ItemGroup>

</Project>
